### ISSUE TITLE
coveralls badge links to 404

### ISSUE THREAD

**Issue by tharvik** [ldsec/drynx#17]
27455b9 sed'ed lca1 to ldsec, travis and goreport seems to not have issues with it, coveralls does: it can't find the repo.

**Comment by katkad** [comment]
Hello, what do you see when you log into coveralls? Do you see this repo as added?

**Comment by tharvik** [comment]
https://coveralls.io/github/ldsec gives me a single repo, "unlynx" (but no logs); using https://coveralls.io/github/lca1 gives me more repos but not at the correct address.

**Comment by katkad** [comment]
What repos do you see here? https://coveralls.io/repos/new

**Comment by tharvik** [comment]
@katkad I'm not owner of the coveralls.io, just found the issue, I can't fix it myself.

**Comment by JoaoAndreSa** [comment]
@tharvik so I think I fixed the issue. Problem is that with the lab name change (and correspondent repository name change) coveralls got disabled for the drynx repo. I manually restart it. It should work now.

**Comment by tharvik** [comment]
@JoaoAndreSa it indeed works, thanks :)
